#!/usr/bin/env bash
# create_pr.sh - Creates and optionally auto-merges PR for state file changes
# Part of the upstream-checker composite action.
set -euo pipefail

#═══════════════════════════════════════════════════════════════
# Commit and Push
#═══════════════════════════════════════════════════════════════

# Generate unique branch name
BRANCH="deps/upstream-$(date +%Y%m%d-%H%M%S)-$RANDOM"
BASE_BRANCH="${GITHUB_REF#refs/heads/}"

echo "🔀 Creating branch: $BRANCH"

# Configure git
git config user.name "github-actions[bot]"
git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

# Create and switch to new branch
git checkout -b "$BRANCH"

# Stage state file
git add "$STATE_FILE"

# Stage go.mod / go.sum if they were modified
if [[ -f "go.mod" ]] && git diff --name-only | grep -qE '^go\.(mod|sum)$'; then
  git add go.mod go.sum
fi
# Also check staged changes
if git diff --cached --name-only | grep -qE '^go\.(mod|sum)$'; then
  : # already staged
fi

RUN_URL="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
FOOTER="---
*Auto-generated by [upstream-checker](${RUN_URL})*"

if [[ "$IS_INIT" == "true" ]]; then
  PR_TITLE="chore(deps): initialize upstream dependency tracking"
  PR_BODY="## Initial Dependencies

${INIT_SUMMARY}

${FOOTER}"
else
  PR_TITLE="chore(deps): update upstream dependencies"
  PR_BODY="## Updated Dependencies

${UPDATE_SUMMARY}

${FOOTER}"
fi

git commit -m "$PR_TITLE" -m "$PR_BODY"

# Push branch
echo "📤 Pushing branch..."
git push origin "$BRANCH"

#═══════════════════════════════════════════════════════════════
# Create PR and Merge
#═══════════════════════════════════════════════════════════════

# Create PR with labels
echo "📋 Creating PR..."
PR_ARGS=(--title "$PR_TITLE" --body "$PR_BODY" --base "$BASE_BRANCH" --head "$BRANCH")

IFS=',' read -ra LABEL_ARRAY <<< "$PR_LABELS"
for label in "${LABEL_ARRAY[@]}"; do
  label=$(echo "$label" | xargs)  # trim whitespace
  [[ -n "$label" ]] && PR_ARGS+=(--label "$label")
done

PR_URL=$(gh pr create "${PR_ARGS[@]}")

PR_NUMBER=$(echo "$PR_URL" | grep -oE '[0-9]+$')

echo "✅ Created PR #$PR_NUMBER: $PR_URL"

# Auto-merge if enabled
if [[ "$AUTO_MERGE" == "true" ]]; then
  echo "🔄 Merging PR..."
  gh pr merge "$PR_NUMBER" --merge --delete-branch
  echo "✅ PR merged and branch deleted"
fi

# Set outputs
{
  echo "pr_number=$PR_NUMBER"
  echo "pr_url=$PR_URL"
} >> "$GITHUB_OUTPUT"
